apiVersion: v1
kind: Pod
metadata:
  labels:
    name: nginx
spec:
  containers:
    - image: nginx
      name: ngi
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: service
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 80
      protocol: TCP
      targetPort: 80